### ISSUE TITLE
Escalar - geral: relatório

### ISSUE THREAD

**Issue by gdsantana** [gdsantana/mphw#12]
Realizar um relatório sobre o projeto contendo os seguintes partes:

Capa;
Apresentação do relatório;
Sumário;
Resumo;
Introdução
Objetivo;
Metodologia;
Desenvolvimento;
Laboratório de pesquisa em Geodésia e Centro de Tecnologia Acadêmica;
Sistema Mecânico;
Sistema Eletro-eletrônico;
Sistema de Software;
Conclusões;
Apesar de a realização de um relatório ser algo com baixo rigor, estou aproveitando esta oportunidade para exercitar a utilização da wiki para dar inicio a construção de um artigo sobre o projeto

link do CTA:http://cta.if.ufrgs.br/issues/499

**Comment by fgnievinski** [comment]
abandonada
