### ISSUE TITLE
Escalar - hardware - Sistema de alimentação solar: Verificar duração da bateria - sem recarga

### ISSUE THREAD

**Issue by gdsantana** [gdsantana/mphw#14]
Deixei o equipamento ligado na bateria, sem o painel e regulares solares.
Verificar a duração até desligar, com base nos arquivos de dados gravados.
Ficou ligado desde 20 agosto 2018 às 18 horas (hora local).

![IMG_20180820_174113390_HDR__1_](https://user-images.githubusercontent.com/44853071/95223940-8459c600-07d0-11eb-965a-2d64e75d1cea.jpg)
[arduino_serial_log_20180822_155500.zip](https://github.com/gdsantana/mphw/files/5334966/arduino_serial_log_20180822_155500.zip)
![image](https://user-images.githubusercontent.com/44853071/95223973-8de32e00-07d0-11eb-8de6-07fef51aaef4.png)
![image](https://user-images.githubusercontent.com/44853071/95224008-98052c80-07d0-11eb-9dba-d3c9c80aae67.png)
[Book1.xlsx](https://github.com/gdsantana/mphw/files/5334978/Book1.xlsx)

link do CTA: http://cta.if.ufrgs.br/issues/546

**Comment by fgnievinski** [comment]
resolvida na origem

**Comment by fgnievinski** [comment]
resolvida na origem
