### ISSUE TITLE
Escalar - hardware - Sistema de alimentação solar: Verificar energia da bateria - com recarga solar

### ISSUE THREAD

**Issue by gdsantana** [gdsantana/mphw#15]
Parece que é possível usar o sensor INA219 para monitorar a energia restante na bateria, e não apenas o consumo.

Isso é importante para garantir que a bateria nunca fique sem energia quando não há recarga, como por exemplo de madrugada, ou em períodos com recarga insuficiente, como dias chuvosos.
![IMG_20180822_180809634_HDR](https://user-images.githubusercontent.com/44853071/95224158-c1be5380-07d0-11eb-99ed-017c1ce6ec6c.jpg)
![IMG_20180822_183603711_HDR](https://user-images.githubusercontent.com/44853071/95224192-c84ccb00-07d0-11eb-866b-4b7f95b88698.jpg)
[ardu_serial_log_20180913.zip](https://github.com/gdsantana/mphw/files/5334992/ardu_serial_log_20180913.zip)
![image](https://user-images.githubusercontent.com/44853071/95224273-d7cc1400-07d0-11eb-863e-4972626279c4.png)
a corrente gira em torno de 80mA e 100mA durante a noite. já durante o dia, o carregador solar torna a corrente negativa.

a potencia sobe rapidamente quando o sol nasce, alcançando um pico de 1.5W e permanecendo nesse patamar por algumas horas. depois a potência cai a zero e então sobe até 250mW, aonde permanece ao longo da noite. só cai a zero novamente ao final da madrugada. (não entendo pq não permanece em zero -- capacitor?) o painel solar utilizado tem dimensão de 3.5W, então ou o céu estava nublado, ou o painel solar estava mau orientado.

a tensão de barramento ("bus voltage") indica a tensão da bateria durante a noite e a tensão do carregador solar durante o dia. quando o sol aparece, a tensão é em torno de 3.35V e quando sol se vai é 3.55V. (o sol não aparece logo quando nasce pois há um prédio bloqueando.) ao longo da noite, a tensão vai diminuindo gradualmente, indicando consumo da energia da bateria. o mínimo alcançado foi de 3.35V ao final da madrugada. esse valor é maior que o mínimo aceitável para o arduino funcionar (3.2V), de acordo com a especificação do produto:
https://learn.adafruit.com/adafruit-feather-32u4-adalogger?view=all#measuring-battery-4-8

Hoje o Carlos me ajudou um pouco com o Octave então consegui manipular a matriz para criar o gráfico. Mas fiz o gráfico da corrente versus clock. Olhar arquivo.
![image](https://user-images.githubusercontent.com/44853071/95224295-e31f3f80-07d0-11eb-8429-759bd98e992b.png)

link do CTA:http://cta.if.ufrgs.br/issues/547

**Comment by fgnievinski** [comment]
resolvida na origem
