### ISSUE TITLE
Escalar - hardware - Sistema de alimentação solar: Verificar consumo - sem bateria

### ISSUE THREAD

**Issue by gdsantana** [gdsantana/mphw#16]
O consumo muda muito entre os estados ativo e inativo do circuito. Então é preciso ler o consumo com alta taxa (muitas vezes por segundo). Para que a análise seja viável, a duração precisa ser curta (algumas horas). Também é preciso não usar o recarregador solar, pois a corrente fica negativa quando está carregando. O ideal é alimentanr o circuito através da USB, sem bateria.

![image](https://user-images.githubusercontent.com/44853071/95224786-79536580-07d1-11eb-9a62-a4de16caf0a8.png)
resultado de medição fina, revelando os picos de consumo devido à gravação no cartão SD. o valor médio foi de 90mA. os degraus devem ser devidos ao número de satélites rastreados. a opção DEBUG estava habilitada (infelizmente); refazer com ela desabilitada (ou seja, comentada).

foi determinado que a corrente de consumo baixa de 90mA para 40mA dependendo do firmware do GPS, fornecido pelo seu fabricante (não confundir com firmware do Arduino).

link do CTA:http://cta.if.ufrgs.br/issues/581

**Comment by fgnievinski** [comment]
resolvida na origem
