### ISSUE TITLE
Escalar - hardware - Sistema de alimentação solar: Verificar consumo - na rua

### ISSUE THREAD

**Issue by gdsantana** [gdsantana/mphw#17]
A intenção com essa medição é verificar a performance final do sistema de alimentação. As condições devem ser parecidas com a realidade do usuário final. Também deve ocorrer por longos períodos de tempo (até uma semana). Então vamos dar preferência ao registro da bateria em cartão SD pelo próprio circuito (arquivo BATTERY.TXT), porém com atualização infrequente (a cada minuto). Não será usado o sensor de corrente INA219. Idealmente a instalação será no telhado, com o painel solar desobstruído.

![image](https://user-images.githubusercontent.com/44853071/95225092-ca635980-07d1-11eb-973a-6ba988a6fc4f.png)

Verificação do consumo no período de 30/10 a 13/11 de 2018.
Utilizamos o menor painel.

A tensão mínima foi de 3.5 V. Isso ainda é acima do mínimo para o Arduino funcionar, que é 3,2 V (aproximadamente). Porém há vários espaços na horizontal, que representam descontinuidade no período e falta de energia para o dispositivo. Neste caso, conclui-se mais uma vez que o painel pequeno é insuficiente.

link do CTA:http://cta.if.ufrgs.br/issues/582

**Comment by fgnievinski** [comment]
resolvida na origem
